Add MoviePlaybackSample for Swift 2.2
toshi0383/TVMLKitchen pull request #131
Opened 2017-01-06 20:40 UTC by Wei-Xia

2017-01-06 23:11 UTC, toshi0383 commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2017-01-06 23:21 UTC, toshi0383 commented
Tested on Xcode7.3.1. TVMLKit fails to parse the xmlString. Could you look at it?
```
2017-01-07 08:19:15.763 MoviePlaybackSample[6519:228833] ITML <Error>: Error Domain=ITMLKitErrorDomain Code=200 "Entity: line 1: parser error : Start tag expected, '<' not found
Optional(<3c3f786d 6c207665 7273696f 6e3d2231 2e302220 656e636f 64696e67 3d22555
^
```

2017-01-06 23:22 UTC, toshi0383 commented on MoviePlaybackSample/AppDelegate.swift
> +    }
Functions above are not necessary. Could you delete these lines?

2017-01-06 23:24 UTC, toshi0383 requested changes

2017-01-06 23:24 UTC, toshi0383 commented on MoviePlaybackSample/AppDelegate.swift
> +    var window: UIWindow?
This property is not necessary.

2017-01-06 23:24 UTC, toshi0383 commented on MoviePlaybackSample/AppDelegate.swift
> +    {
Could you put opening brace in same line?

2017-01-06 23:24 UTC, toshi0383 commented on MoviePlaybackSample/AppDelegate.swift
> +        {
Could you put opening brace in same line?

2017-01-08 22:16 UTC, Wei-Xia commented
Hi @toshi0383, I have changed my code as your suggestions.

About error, YES, I do receive error message from Xcode 7.3 as below.
```
2017-01-06 21:32:18.596 MoviePlaybackSample[1380:18852] ITML <Error>: Error Domain=ITMLKitErrorDomain Code=200 "Entity: line 1: parser error : Start tag expected, '<' not found
Optional(<3c3f786d 6c207665 7273696f 6e3d2231 2e302220 656e636f 64696e67 3d22555
^
" UserInfo={NSLocalizedDescription=Entity: line 1: parser error : Start tag expected, '<' not found
Optional(<3c3f786d 6c207665 7273696f 6e3d2231 2e302220 656e636f 64696e67 3d22555
^
} - file:///Users/weixia/Library/Developer/Xcode/DerivedData/TVMLKitchen-dfsluypjpahpfkglmlxkmjhoonyi/Build/Products/Debug-appletvsimulator/TVMLKitchen.framework/kitchen.js - line:119:37
```

However, I use the exactly same code in my own project with `swift 2.2`, which works perfectly correctly. 
But in this `MoviePlaybackSample`, it can't work. That's really confusing. I will try my best to figure out how to solve this issue.

2017-01-09 23:22 UTC, toshi0383 commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2017-01-09 23:28 UTC, toshi0383 commented
@Wei-Xia 
Thanks for update!
As you can see from the error message,
```
Optional(<3c3f786d 6c207665 7273696f 6e3d2231 2e302220 656e636f 64696e67 3d22555
^
```
The bug is caused by this line. 
```
    return String(data)
```
This produces a String like `Optional(<0xdatadatadata...`, not correct String representation.
Please fix it to parse NSData correctly.
```
    return NSString(data: data!, encoding: NSUTF8StringEncoding)! as String
```

2017-01-09 23:29 UTC, toshi0383 commented
I closed and reopened the PR by mistake. No offense...

2017-01-10 01:34 UTC, Wei-Xia commented
@toshi0383 

Yes, the error message is caused by `string`. I have changed as your suggestion, and it runs very well.

I don't know why the checks by Github/Bitrise was failed, but I can run it successfully locally.

2017-01-10 04:16 UTC, Wei-Xia commented
I downloaded the repo from Github directly, and tried to run it.

It showed the error message below.
<img width="881" alt="screen shot 2017-01-09 at 23 11 43" src="https://cloud.githubusercontent.com/assets/9309906/21793635/10d53f14-d6c1-11e6-8707-515c4b6d5f02.png">

I believe this is the main reason causing failure in Github/Bitrise.

But from my own repository which I commit to this PR, there is no such error message happened. 

I will check with it tomorrow. 🤔

2017-01-10 04:35 UTC, toshi0383 commented
@Wei-Xia 
Thank you very much for your work. It looks great!
I currently set the default VM to be Xcode8.1, so it's ok for Bitrise failure for swift2.2 branch.

p.s. Bitrise does not handle different version of Xcodes at a time. You have to set manually from the web console, then trigger rebuild. And unfortunately, only the admin can see the web console, which is only me for this repo..  So you don't have to worry about the CI 😉

2017-01-10 04:36 UTC, toshi0383 commented
> I downloaded the repo from Github directly, and tried to run it.

Try building `TVMLKitchen` first before building `MoviePlaybackSample`.

2017-01-10 04:36 UTC, merged